#!/usr/bin/env sh
set -e

exists() { [ -e "$1" ]; }

echo "[pre-commit] lint-staged"
npx --no-install lint-staged

# Preventing prettier errors
npm run format

if exists apps/frontend/package.json; then
  echo "[pre-commit] frontend"
  npm run -s precommit:frontend || exit 1
else
  echo "[pre-commit] skip frontend (missing)"
fi

if exists apps/backend/composer.json; then
  echo "[pre-commit] backend"
  npm run -s precommit:backend || exit 1
else
  echo "[pre-commit] skip backend (missing)"
fi
