/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedLoginRouteImport } from './routes/_authenticated/login';

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedLoginRoute = AuthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/profile': typeof ProfileRoute;
  '/login': typeof AuthenticatedLoginRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/profile': typeof ProfileRoute;
  '/login': typeof AuthenticatedLoginRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/profile': typeof ProfileRoute;
  '/_authenticated/login': typeof AuthenticatedLoginRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/profile' | '/login';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/profile' | '/login';
  id: '__root__' | '/' | '/_authenticated' | '/profile' | '/_authenticated/login';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  ProfileRoute: typeof ProfileRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/login': {
      id: '/_authenticated/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof AuthenticatedLoginRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLoginRoute: typeof AuthenticatedLoginRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLoginRoute: AuthenticatedLoginRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ProfileRoute: ProfileRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
